# Generated by Django 2.2.4 on 2021-02-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_video_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
